export * from "./about-kate";
export * from "./applications";
export * from "./boot";
export * from "./game";
export * from "./home";
export * from "./licence";
export * from "./load-screen";
export * from "./media";
export * from "./view-media";
